language: python
python:
    - "2.6"
    - "2.7"
    - "3.1"
    - "3.2"
    - "3.3"
install:
    - pip install . --use-mirrors
script:
    - python setup.py build -i
    - python setup.py test
notifications:
    email:
        on_success: change
        on_failure: change
