language: python
python:
    - "2.6"
    - "2.7"
install:
    - pip install -r .travis-requirements.txt
    - pip install --editable --use-mirrors .
script:
    - make test
notifications:
    email:
        on_success: change
        on_failure: change
